### ISSUE TITLE
Separate streamlit from `update-logs`

### ISSUE THREAD

**Issue by mjennings061** [mjennings061/viking-log-keeper#49]
As a user, I want to `update-logs` without requirement for streamlit, so that I can avoid the bug below:

![image](https://github.com/mjennings061/viking-log-keeper/assets/24479573/379d9b06-52ae-421a-b951-e0acc9204f72)

**Comment by mjennings061** [comment]
Recreated using `update-logs`

```bash
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\git\viking-log-keeper\.venv\Scripts\update-logs.exe\__main__.py", line 4, in <module>
  File "C:\git\viking-log-keeper\src\log_keeper\main.py", line 14, in <module>
    from dashboard.main import AuthConfig
  File "C:\git\viking-log-keeper\src\dashboard\main.py", line 13, in <module>
    from extra_streamlit_components import CookieManager
  File "C:\git\viking-log-keeper\.venv\Lib\site-packages\extra_streamlit_components\__init__.py", line 3, in <module>
    from .TabBar import tab_bar
  File "C:\git\viking-log-keeper\.venv\Lib\site-packages\extra_streamlit_components\TabBar\__init__.py", line 10, in <module>
    _component_func = components.declare_component("tab_bar", path=build_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\viking-log-keeper\.venv\Lib\site-packages\streamlit\components\v1\component_registry.py", line 87, in declare_component
    get_instance().component_registry.register_component(component)
    ^^^^^^^^^^^^^^
  File "C:\git\viking-log-keeper\.venv\Lib\site-packages\streamlit\runtime\__init__.py", line 28, in get_instance
    return Runtime.instance()
           ^^^^^^^^^^^^^^^^^^
  File "C:\git\viking-log-keeper\.venv\Lib\site-packages\streamlit\runtime\runtime.py", line 163, in instance
    raise RuntimeError("Runtime hasn't been created!")
RuntimeError: Runtime hasn't been created!
```
